import { readFileSync } from "node:fs";
import { fileURLToPath } from "node:url";
import { describe, expect, it } from "vitest";
import { EXAMPLE_SPEC, fromJson, generate, toJson, validate } from "./graphspec";

// The shared golden fixtures generated by the Python side — the TS mirror must match them.
const FX = fileURLToPath(new URL("../../../tests/fixtures/graphspec/", import.meta.url));
const readSpec = (n: string) => JSON.parse(readFileSync(`${FX}${n}.json`, "utf8"));
const readText = (f: string) => readFileSync(`${FX}${f}`, "utf8");

describe("TS mirror stays byte-identical to the Python golden fixtures", () => {
  it.each(["linear", "router_cycle", "with_code", "side_effects"])(
    "codegen(%s) matches the golden .py",
    (name) => {
      expect(generate(readSpec(name))).toBe(readText(`${name}.py`));
    },
  );

  it.each(["over_allocation", "side_effect_bad"])(
    "validator messages match the golden error fixture (%s)",
    (name) => {
      expect(validate(readSpec(name)).errors).toEqual(JSON.parse(readText(`${name}.errors.json`)));
    },
  );

  it("the bundled example validates with a cycle note and no errors", () => {
    const r = validate(EXAMPLE_SPEC);
    expect(r.ok).toBe(true);
    expect(r.notes.some((n) => n.includes("Cycle detected"))).toBe(true);
  });

  it("spec ↔ JSON round-trips", () => {
    expect(fromJson(toJson(EXAMPLE_SPEC))).toEqual(EXAMPLE_SPEC);
  });
});
