"use client";

import { useEffect, useRef } from "react";

// Exact HTML of the code + receipt panes (preserved as strings; .codepane has no white-space rule
// in the design, so it renders as the design does). Do not "fix" spacing here — match the source.
const CODE_HTML = `<span class="c"># generated by breakerbox builder — edit freely, it's yours</span>
<span class="k">from</span> langgraph.graph <span class="k">import</span> StateGraph, START, END
<span class="k">from</span> langgraph.checkpoint.memory <span class="k">import</span> MemorySaver
<span class="k">from</span> breakerbox <span class="k">import</span> guard

<span class="k">def</span> <span class="f">planner</span>(state):   <span class="c"># model: gpt-4o · sub_budget=$0.40</span>
    ...  <span class="c"># TODO: your planner logic</span>
    <span class="k">return</span> state

<span class="k">def</span> <span class="f">writer</span>(state):    <span class="c"># model: claude-sonnet · sub_budget=$0.35</span>
    ...
    <span class="k">return</span> state

builder = StateGraph(<span class="f">dict</span>)
builder.add_node(<span class="s">"planner"</span>, planner)
builder.add_node(<span class="s">"writer"</span>, writer)
builder.add_edge(START, <span class="s">"planner"</span>)

app = <span class="f">guard</span>(
    builder.compile(checkpointer=MemorySaver()),
    budget_usd=<span class="s">0.90</span>, velocity_usd_per_min=<span class="s">2.0</span>,
    sub_budgets={<span class="s">"planner"</span>: <span class="s">0.40</span>, <span class="s">"writer"</span>: <span class="s">0.35</span>},
    on_trip=<span class="s">"pause"</span>,
)`;

const RECEIPT_HTML = `<div class="big"><b>run receipt</b> · research_pipeline · <em>tripped at hop 12</em> · spent <b>$0.82</b> of $0.90</div>
<div class="rline"><span>hop 1</span><span>planner</span><span class="bar"><i style="width:8%"></i></span><span class="amt">$0.06</span></div>
<div class="rline"><span>hop 2</span><span>web_search</span><span class="bar"><i style="width:2%"></i></span><span class="amt">$0.00</span></div>
<div class="rline"><span>hop 3</span><span>writer</span><span class="bar"><i style="width:12%"></i></span><span class="amt">$0.09</span></div>
<div class="rline"><span>hop 5</span><span>planner ↺</span><span class="bar"><i style="width:9%"></i></span><span class="amt">$0.07</span></div>
<div class="rline"><span>hop 7</span><span>writer ↺</span><span class="bar"><i style="width:15%"></i></span><span class="amt">$0.11</span></div>
<div class="rline hot"><span>hop 9</span><span>planner ↺</span><span class="bar"><i style="width:20%"></i></span><span class="amt">$0.14</span></div>
<div class="rline hot"><span>hop 11</span><span>writer ↺</span><span class="bar"><i style="width:27%"></i></span><span class="amt">$0.19</span></div>
<div class="rline stop"><span>⏻</span><span colspan="2">tripped — velocity · next hop blocked · state checkpointed · 0 side effects fired</span><span></span><span class="amt">$0.82</span></div>`;

export default function ProductWindow() {
  const root = useRef<HTMLDivElement>(null);

  useEffect(() => {
    const el = root.current;
    if (!el) return;
    const reduce = matchMedia("(prefers-reduced-motion: reduce)").matches;
    const q = <T extends Element>(sel: string) => el.querySelector(sel) as T;

    // --- tab switching (verbatim behavior) ---
    const tabs = [...el.querySelectorAll<HTMLButtonElement>(".tab")];
    const panes = [...el.querySelectorAll<HTMLElement>(".pane")];
    const onTab = (t: HTMLButtonElement) => () => {
      tabs.forEach((x) => {
        x.classList.toggle("on", x === t);
        x.setAttribute("aria-selected", String(x === t));
      });
      panes.forEach((pn) => pn.classList.toggle("on", pn.dataset.pane === t.dataset.tab));
    };
    const tabHandlers = tabs.map((t) => {
      const h = onTab(t);
      t.addEventListener("click", h);
      return [t, h] as const;
    });

    // --- canvas run animation (verbatim) ---
    const pulse = q<SVGCircleElement>("#pulse");
    const E: Record<string, SVGPathElement> = {
      e1: q("#e1"),
      e2: q("#e2"),
      e3: q("#e3"),
      e4: q("#e4"),
      eloop: q("#eloop"),
    };
    const c1 = q<SVGTextElement>("#c1"),
      c3 = q<SVGTextElement>("#c3"),
      mfill = q<HTMLElement>("#mfill"),
      mspent = q<HTMLElement>("#mspent"),
      meter = q<HTMLElement>("#meter"),
      toast = q<HTMLElement>("#toast"),
      breaker = q<SVGGElement>("#breaker"),
      live = q<HTMLElement>("#livepill"),
      replay = q<HTMLButtonElement>("#replay"),
      rw = q<HTMLElement>("#rw");

    let spent = 0,
      p = 0,
      w = 0,
      anim: number[] = [];
    const money = (v: number) => "$" + v.toFixed(2);
    const setSpent = (v: number) => {
      spent = v;
      mspent.textContent = money(spent) + " spent";
      mfill.style.width = Math.min(100, (spent / 0.9) * 100) + "%";
    };
    function travel(edge: string, dur: number, cb?: () => void) {
      if (reduce) {
        cb?.();
        return;
      }
      const path = E[edge],
        len = path.getTotalLength();
      let t0: number | null = null;
      pulse.style.opacity = "1";
      function fr(ts: number) {
        if (!t0) t0 = ts;
        const k = Math.min(1, (ts - t0) / dur);
        const pt = path.getPointAtLength(k * len);
        pulse.setAttribute("cx", String(pt.x));
        pulse.setAttribute("cy", String(pt.y));
        if (k < 1) {
          anim.push(requestAnimationFrame(fr));
        } else {
          pulse.style.opacity = "0";
          cb?.();
        }
      }
      anim.push(requestAnimationFrame(fr));
    }
    function seq(steps: ((done: () => void) => void)[], i: number) {
      if (i >= steps.length) return;
      steps[i](() => seq(steps, i + 1));
    }
    function reset() {
      anim.forEach(cancelAnimationFrame);
      anim = [];
      setSpent(0);
      p = 0;
      w = 0;
      c1.textContent = "$0.00";
      c3.textContent = "$0.00";
      E.eloop.setAttribute("stroke", "#3a424c");
      breaker.setAttribute("opacity", "0");
      meter.classList.remove("hot");
      rw.classList.remove("hot");
      toast.classList.remove("show");
      replay.hidden = true;
      live.textContent = "● live run";
      live.style.color = "";
      live.style.borderColor = "";
    }
    function trip(done?: () => void) {
      setSpent(0.82);
      E.eloop.setAttribute("stroke", "#d4a017");
      breaker.setAttribute("opacity", "1");
      meter.classList.add("hot");
      rw.classList.add("hot");
      toast.classList.add("show");
      live.textContent = "⏻ tripped";
      live.style.color = "#d4a017";
      live.style.borderColor = "#d4a017";
      replay.hidden = false;
      done?.();
    }
    function run() {
      reset();
      if (reduce) {
        c1.textContent = "$0.31";
        c3.textContent = "$0.51";
        trip();
        return;
      }
      const bump = (node: string, amt: number) => (done: () => void) => {
        if (node === "p") {
          p += amt;
          c1.textContent = money(p);
        } else {
          w += amt;
          c3.textContent = money(w);
        }
        setSpent(spent + amt);
        setTimeout(done, 140);
      };
      const loopPass = (amt: number, dur: number) => (done: () => void) =>
        travel("eloop", dur, () => {
          bump("p", amt)(() => travel("e2", dur * 0.6, () => bump("w", amt * 1.4)(done)));
        });
      seq(
        [
          (done) => setTimeout(done, 600),
          bump("p", 0.06),
          (done) => travel("e1", 700, done),
          (done) => travel("e2", 700, done),
          bump("w", 0.09),
          (done) => travel("e4", 600, done),
          loopPass(0.05, 900),
          loopPass(0.07, 700),
          (done) => {
            rw.classList.add("hot");
            meter.classList.add("hot");
            loopPass(0.09, 520)(done);
          },
          loopPass(0.11, 380),
          trip,
        ],
        0,
      );
    }
    const onReplay = () => run();
    replay.addEventListener("click", onReplay);
    const so = new IntersectionObserver(
      (x) => {
        if (x[0].isIntersecting) {
          run();
          so.disconnect();
        }
      },
      { threshold: 0.35 },
    );
    so.observe(el);

    return () => {
      anim.forEach(cancelAnimationFrame);
      tabHandlers.forEach(([t, h]) => t.removeEventListener("click", h));
      replay.removeEventListener("click", onReplay);
      so.disconnect();
    };
  }, []);

  return (
    <div className="stage">
      <div className="window" id="stage" ref={root}>
        <div className="winbar">
          <span className="dot" />
          <span className="dot" />
          <span className="dot" />
          <div className="tabs" role="tablist" aria-label="Product views">
            <button className="tab on" role="tab" aria-selected="true" data-tab="canvas">
              canvas
            </button>
            <button className="tab" role="tab" aria-selected="false" data-tab="code">
              generated python
            </button>
            <button className="tab" role="tab" aria-selected="false" data-tab="receipt">
              receipt
            </button>
          </div>
          <span className="live" id="livepill">
            ● live run
          </span>
        </div>

        <div className="pane on" data-pane="canvas">
          <div className="stagebody">
            <div className="canvas">
              <svg
                viewBox="0 0 700 400"
                role="img"
                aria-label="An agent graph running: cost flows between nodes until the loop trips the breaker"
              >
                <defs>
                  <marker id="ah" viewBox="0 0 10 10" refX="8" refY="5" markerWidth="7" markerHeight="7" orient="auto">
                    <path d="M2 1L8 5L2 9" fill="none" stroke="#3a424c" strokeWidth="1.5" strokeLinecap="round" />
                  </marker>
                </defs>
                <g stroke="#3a424c" strokeWidth="1.8" fill="none">
                  <path id="e1" d="M178 128 C 240 128, 250 96, 306 96" markerEnd="url(#ah)" />
                  <path id="e2" d="M178 148 C 240 148, 250 208, 306 208" markerEnd="url(#ah)" />
                  <path id="e3" d="M446 96 C 500 96, 508 138, 546 138" markerEnd="url(#ah)" />
                  <path id="e4" d="M446 208 C 500 208, 508 168, 546 168" markerEnd="url(#ah)" />
                  <path id="eloop" d="M610 190 C 640 300, 300 330, 130 300 C 90 292, 92 200, 108 168" markerEnd="url(#ah)" strokeDasharray="5 6" />
                </g>
                <g fontFamily="JetBrains Mono,monospace">
                  <g>
                    <rect x="70" y="108" width="108" height="58" rx="12" fill="#181c21" stroke="#303841" strokeWidth="1.5" />
                    <text x="124" y="132" textAnchor="middle" fill="#f2f0e9" fontSize="14" fontWeight="500">planner</text>
                    <text x="124" y="152" textAnchor="middle" fill="#98a1ad" fontSize="11" id="c1">$0.00</text>
                  </g>
                  <g>
                    <rect x="306" y="68" width="140" height="56" rx="12" fill="#181c21" stroke="#303841" strokeWidth="1.5" />
                    <text x="376" y="91" textAnchor="middle" fill="#f2f0e9" fontSize="14" fontWeight="500">web_search</text>
                    <text x="376" y="110" textAnchor="middle" fill="#98a1ad" fontSize="11">tool · safe</text>
                  </g>
                  <g>
                    <rect x="306" y="180" width="140" height="56" rx="12" fill="#181c21" stroke="#303841" strokeWidth="1.5" />
                    <text x="376" y="203" textAnchor="middle" fill="#f2f0e9" fontSize="14" fontWeight="500">writer</text>
                    <text x="376" y="222" textAnchor="middle" fill="#98a1ad" fontSize="11" id="c3">$0.00</text>
                  </g>
                  <g>
                    <rect x="546" y="110" width="118" height="80" rx="12" fill="#181c21" stroke="#303841" strokeWidth="1.5" />
                    <text x="605" y="140" textAnchor="middle" fill="#f2f0e9" fontSize="14" fontWeight="500">publish</text>
                    <text x="605" y="160" textAnchor="middle" fill="#d4a017" fontSize="10.5">side-effecting</text>
                    <text x="605" y="177" textAnchor="middle" fill="#98a1ad" fontSize="11">gated</text>
                  </g>
                </g>
                <g id="breaker" opacity="0">
                  <circle cx="368" cy="316" r="17" fill="#0f1114" stroke="#d4a017" strokeWidth="2" />
                  <path d="M361 322 L368 310 L366 316 L375 310" stroke="#d4a017" strokeWidth="2.2" fill="none" strokeLinecap="round" strokeLinejoin="round" />
                </g>
                <circle id="pulse" r="4.5" fill="#d4a017" opacity="0" />
              </svg>
            </div>
            <aside className="side">
              {/* fix #3: decorative mock label, not a document heading (avoids h1→h4 skip) */}
              <div className="side-h4">Budget tree</div>
              <div className="tree">
                <div className="trow root">
                  <span className="nm">research_pipeline</span>
                  <span className="amt">$0.90</span>
                </div>
                <div className="trow child">
                  <span className="nm">planner</span>
                  <span className="amt">$0.40</span>
                </div>
                <div className="trow child" id="rw">
                  <span className="nm">writer</span>
                  <span className="amt">$0.35</span>
                </div>
                <div className="trow child">
                  <span className="nm">unallocated</span>
                  <span className="amt">$0.15</span>
                </div>
              </div>
              <div className="meter" id="meter">
                <i id="mfill" />
              </div>
              <div className="mlab">
                <span id="mspent">$0.00 spent</span>
                <span>cap $0.90</span>
              </div>
              <div className="toast" id="toast">
                <b>⏻ tripped</b> — velocity spike on writer→planner loop. Next hop blocked, state
                checkpointed. <b>$0.82</b> spent · <b>$0.08</b> under budget.
              </div>
              <button className="replay" id="replay" hidden>
                ↻ replay the run
              </button>
            </aside>
          </div>
        </div>

        <div className="pane" data-pane="code">
          <div className="codepane" dangerouslySetInnerHTML={{ __html: CODE_HTML }} />
        </div>

        <div className="pane" data-pane="receipt">
          <div className="rcp" dangerouslySetInnerHTML={{ __html: RECEIPT_HTML }} />
        </div>
      </div>
    </div>
  );
}
