"""Codegen: a graph spec -> readable, guarded LangGraph Python (a plain string).

One-directional and pure: spec in, Python text out. Nothing here evaluates, imports, or
executes the spec — the output is meant to be downloaded/copied and run on your machine.
The output is deliberately plain so a human enjoys editing the TODO node bodies.
"""

from __future__ import annotations

import keyword
import re

from breakerbox.ceiling import ceiling_comment, cost_ceiling


def _ident(raw: str, used: set[str]) -> str:
    s = re.sub(r"\W", "_", raw)
    if not s or s[0].isdigit():
        s = "n_" + s
    if keyword.iskeyword(s):
        s += "_"
    base, i = s, 1
    while s in used:
        s = f"{base}_{i}"
        i += 1
    used.add(s)
    return s


# Number formatting is FIELD-aware (not Python-type-aware) so the TS mirror can match it:
# JSON/JS can't tell 5.0 from 5, so we decide float-vs-int by which field it is, not by type.
def _money(v) -> str:
    f = float(v)
    return f"{int(f)}.0" if f.is_integer() else repr(f)


def _int(v) -> str:
    return str(int(v))


def _fmt(v) -> str:  # strings / bools (router labels)
    if isinstance(v, bool):
        return "True" if v else "False"
    if isinstance(v, str):
        return '"' + v.replace("\\", "\\\\").replace('"', '\\"') + '"'
    return repr(v)


# Approved node code (the function body) -> 4-space-indented lines, or None to fall back to the
# TODO stub. MUST stay byte-identical to graphspec.ts:codeBody.
def _code_body(code):
    if not isinstance(code, str):
        return None
    trimmed = code.replace("\r\n", "\n").strip()
    if not trimmed:
        return None
    return ["" if not line.strip() else "    " + line for line in trimmed.split("\n")]


def generate(spec: dict) -> str:
    config = spec.get("config", {})
    nodes = spec.get("nodes", [])
    edges = spec.get("edges", [])

    start_id = next((n["id"] for n in nodes if n.get("type") == "start"), None)
    end_ids = {n["id"] for n in nodes if n.get("type") == "end"}

    used: set[str] = set()
    fn_of: dict[str, str] = {}
    for n in nodes:
        if n.get("type") in ("model", "tool", "router"):
            fn_of[n["id"]] = _ident(n["id"], used)

    lines: list[str] = [
        "# Generated by Breakerbox Builder. Edit the node bodies marked TODO.",
        *ceiling_comment(cost_ceiling(spec)),
        "from langgraph.graph import END, START, StateGraph",
        "from langgraph.checkpoint.memory import MemorySaver",
        "",
        "from breakerbox import guard",
        "",
    ]

    # one function per model/tool/router node (+ a route function per router)
    for n in nodes:
        t = n.get("type")
        fn = fn_of.get(n["id"])
        if t == "model":
            mt = n.get("max_tokens", "default")
            sb = f"${n['sub_budget_usd']:.2f}" if "sub_budget_usd" in n else "unset"
            body = _code_body(n.get("code")) or [
                "    # TODO: call your model here and update state",
                "    return state",
            ]
            lines += [
                "",
                f"def {fn}(state):  # model: {n.get('model')} · max_tokens={mt} · sub_budget={sb}",
                *body,
                "",
            ]
        elif t == "tool":
            name = n.get("name")
            sec = n.get("side_effect_class")
            # side_effect_class is the source of truth when set (read = safe); else the boolean.
            se = sec != "read" if sec else bool(n.get("side_effecting"))
            comment = f"# tool: {name} · side_effecting={se}"
            if sec:
                comment += f" · class={sec}"
            body = _code_body(n.get("code")) or [
                f"    # TODO: run the {name} tool and update state",
                "    return state",
            ]
            lines += [
                "",
                f"def {fn}(state):  {comment}",
                *body,
                "",
            ]
        elif t == "router":
            labels = [e.get("condition") for e in edges if e.get("source") == n["id"]]
            default = _fmt(labels[0]) if labels else '"pass"'
            body = _code_body(n.get("code")) or [
                "    # TODO: (optional) prep state before routing",
                "    return state",
            ]
            lines += [
                "",
                f"def {fn}(state):  # router: {n.get('condition') or 'route'}",
                *body,
                "",
                "",
                f"def {fn}_route(state):",
                f"    # TODO: return one of: {', '.join(str(x) for x in labels)}",
                f"    return {default}",
                "",
            ]

    lines += ["", "builder = StateGraph(dict)"]
    for n in nodes:
        if n["id"] in fn_of:
            lines.append(f'builder.add_node("{n["id"]}", {fn_of[n["id"]]})')

    router_ids = {n["id"] for n in nodes if n.get("type") == "router"}

    def _dst(target: str) -> str:
        return "END" if target in end_ids else f'"{target}"'

    for e in edges:
        s, t = e.get("source"), e.get("target")
        if s in router_ids:
            continue  # emitted as conditional edges below
        src = "START" if s == start_id else f'"{s}"'
        lines.append(f"builder.add_edge({src}, {_dst(t)})")

    for rid in [n["id"] for n in nodes if n.get("type") == "router"]:
        mapping = ", ".join(
            f"{_fmt(e.get('condition'))}: {_dst(e.get('target'))}"
            for e in edges
            if e.get("source") == rid
        )
        lines.append(f'builder.add_conditional_edges("{rid}", {fn_of[rid]}_route, {{{mapping}}})')

    # guard(...) — only the config keys that are present
    kw = []
    if "budget_usd" in config:
        kw.append(f"    budget_usd={_money(config['budget_usd'])},")
    if "max_hops" in config:
        kw.append(f"    max_hops={_int(config['max_hops'])},")
    if "ttl_seconds" in config:
        kw.append(f"    ttl_seconds={_int(config['ttl_seconds'])},")
    if "velocity_usd_per_min" in config:
        kw.append(f"    velocity_usd_per_min={_money(config['velocity_usd_per_min'])},")
    if "on_trip" in config:
        kw.append(f'    on_trip="{config["on_trip"]}",')
    sub = {n["id"]: n["sub_budget_usd"] for n in nodes
           if n.get("type") == "model" and "sub_budget_usd" in n}
    if sub:
        items = ", ".join(f'"{k}": {_money(v)}' for k, v in sub.items())
        kw.append(f"    sub_budgets={{{items}}},")

    # Destructive tools get a human-approval gate baked into the compiled graph: LangGraph pauses
    # before those nodes so a person must resume. Safety made static — visible in the code you own.
    destructive = [
        n["id"] for n in nodes
        if n.get("type") == "tool" and n.get("side_effect_class") == "destructive"
    ]
    if destructive:
        ids = ", ".join(f'"{i}"' for i in destructive)
        compile_line = f"    builder.compile(checkpointer=MemorySaver(), interrupt_before=[{ids}]),"
        approval_note = [
            "# Destructive tools pause for human approval before running (interrupt_before)."
        ]
    else:
        compile_line = "    builder.compile(checkpointer=MemorySaver()),"
        approval_note = []

    lines += [
        "",
        *approval_note,
        "app = guard(",
        compile_line,
        *[line for line in kw if line],
        ")",
        "",
        'if __name__ == "__main__":',
        "    print(app.invoke({}))",
        "",
    ]
    return "\n".join(lines)
