"""Refresh prices.json from LiteLLM's community-maintained price table.

LiteLLM publishes per-token costs for ~2000 chat models and keeps them current. We map
their `input_cost_per_token`/`output_cost_per_token` (USD per token) to our per-million-token
schema and write prices.json. The bundled file stays the offline fallback; this just keeps it
fresh. Run via `agentbreaker update-prices`.
"""

from __future__ import annotations

import datetime
import json
import urllib.request
from pathlib import Path

DEFAULT_SOURCE = (
    "https://raw.githubusercontent.com/BerriAI/litellm/main/"
    "model_prices_and_context_window.json"
)
_DEFAULT_RATE = {"in_per_mtok_usd": 5.00, "out_per_mtok_usd": 15.00}
_PRICEABLE_MODES = ("chat", "completion")


def _bundled_path() -> Path:
    return Path(__file__).with_name("prices.json")


def fetch(source: str = DEFAULT_SOURCE) -> dict:
    req = urllib.request.Request(source, headers={"User-Agent": "agentbreaker/price-update"})
    with urllib.request.urlopen(req, timeout=30) as resp:
        return json.loads(resp.read())


def build_models(data: dict) -> dict[str, dict]:
    """Map the LiteLLM table to `{provider/model: {in_per_mtok_usd, out_per_mtok_usd}}`."""
    models: dict[str, dict] = {}
    for name, spec in data.items():
        if name == "sample_spec" or not isinstance(spec, dict):
            continue
        if spec.get("mode") not in _PRICEABLE_MODES:
            continue
        cin, cout = spec.get("input_cost_per_token"), spec.get("output_cost_per_token")
        if not isinstance(cin, (int, float)) or not isinstance(cout, (int, float)):
            continue
        provider = spec.get("litellm_provider")
        # LiteLLM keys are sometimes already "provider/model", sometimes bare.
        key = name if "/" in name else f"{provider}/{name}" if provider else name
        models[key] = {
            "in_per_mtok_usd": round(cin * 1_000_000, 6),
            "out_per_mtok_usd": round(cout * 1_000_000, 6),
        }
    return dict(sorted(models.items()))


def _existing_default_rate(path: Path) -> dict:
    if path.exists():
        try:
            return json.loads(path.read_text()).get("default_rate") or _DEFAULT_RATE
        except (json.JSONDecodeError, OSError):
            pass
    return _DEFAULT_RATE


def build_table(data: dict, source: str, default_rate: dict) -> dict:
    return {
        "version": datetime.date.today().isoformat(),
        "_source": source,
        "_note": "Generated by `agentbreaker update-prices` from LiteLLM. USD per 1M tokens.",
        "models": build_models(data),
        "default_rate": default_rate,
    }


def run(source: str = DEFAULT_SOURCE, output: str | None = None, dry_run: bool = False) -> int:
    out = Path(output) if output else _bundled_path()
    table = build_table(fetch(source), source, _existing_default_rate(out))
    new = table["models"]

    if dry_run:
        old = json.loads(out.read_text()).get("models", {}) if out.exists() else {}
        added = set(new) - set(old)
        removed = set(old) - set(new)
        changed = [k for k in set(new) & set(old) if new[k] != old[k]]
        print(f"models: {len(new)} (was {len(old)})  +{len(added)} -{len(removed)} ~{len(changed)}")
        for k in sorted(changed)[:15]:
            print(f"  ~ {k}: {old[k]} -> {new[k]}")
        return 0

    payload = json.dumps(table, indent=2) + "\n"
    out.write_text(payload)
    print(f"wrote {len(new)} models to {out}")
    # keep the dashboard's copy in sync when running from the repo (locked by pricing.test.ts)
    dash = Path(__file__).resolve().parents[2] / "cloud" / "dashboard" / "lib" / "prices.json"
    if dash.exists():
        dash.write_text(payload)
        print(f"synced dashboard copy: {dash}")
    return 0
