# Generated by Breakerbox Builder. Edit the node bodies marked TODO.
from langgraph.graph import END, START, StateGraph
from langgraph.checkpoint.memory import MemorySaver

from agentbreaker import guard


def planner(state):  # model: openai/gpt-4o · max_tokens=1024 · sub_budget=$2.00
    # TODO: call your model here and update state
    return state


def search(state):  # tool: web_search · side_effecting=False
    # TODO: run the web_search tool and update state
    return state


def writer(state):  # model: anthropic/claude-sonnet-4-6 · max_tokens=2048 · sub_budget=$1.50
    # TODO: call your model here and update state
    return state


def publish(state):  # tool: post_to_cms · side_effecting=True
    # TODO: run the post_to_cms tool and update state
    return state


def router(state):  # router: quality_check
    # TODO: (optional) prep state before routing
    return state


def router_route(state):
    # TODO: return one of: pass, retry
    return "pass"


builder = StateGraph(dict)
builder.add_node("planner", planner)
builder.add_node("search", search)
builder.add_node("writer", writer)
builder.add_node("publish", publish)
builder.add_node("router", router)
builder.add_edge(START, "planner")
builder.add_edge("planner", "search")
builder.add_edge("search", "writer")
builder.add_edge("writer", "router")
builder.add_edge("publish", END)
builder.add_conditional_edges("router", router_route, {"pass": "publish", "retry": "planner"})

app = guard(
    builder.compile(checkpointer=MemorySaver()),
    budget_usd=5.0,
    max_hops=50,
    ttl_seconds=600,
    velocity_usd_per_min=2.0,
    on_trip="pause",
    sub_budgets={"planner": 2.0, "writer": 1.5},
)

if __name__ == "__main__":
    print(app.invoke({}))
