# Generated by Breakerbox Builder. Edit the node bodies marked TODO.
# Cost ceiling: ≤ $0.00 (no priced model steps).
from langgraph.graph import END, START, StateGraph
from langgraph.checkpoint.memory import MemorySaver

from breakerbox import guard


def fetch(state):  # tool: read_docs · side_effecting=False · class=read
    # TODO: run the read_docs tool and update state
    return state


def call_api(state):  # tool: call_api · side_effecting=True · class=network
    # TODO: run the call_api tool and update state
    return state


def save(state):  # tool: save_draft · side_effecting=True · class=write
    # TODO: run the save_draft tool and update state
    return state


def delete(state):  # tool: delete_records · side_effecting=True · class=destructive
    # TODO: run the delete_records tool and update state
    return state


builder = StateGraph(dict)
builder.add_node("fetch", fetch)
builder.add_node("call_api", call_api)
builder.add_node("save", save)
builder.add_node("delete", delete)
builder.add_edge(START, "fetch")
builder.add_edge("fetch", "call_api")
builder.add_edge("call_api", "save")
builder.add_edge("save", "delete")
builder.add_edge("delete", END)

# Destructive tools pause for human approval before running (interrupt_before).
app = guard(
    builder.compile(checkpointer=MemorySaver(), interrupt_before=["delete"]),
    budget_usd=5.0,
    max_hops=20,
    on_trip="pause",
)

if __name__ == "__main__":
    print(app.invoke({}))
