# Generated by Breakerbox Builder. Edit the node bodies marked TODO.
# ⚠ Cost ceiling: UNBOUNDED — a reachable loop has no max_hops; only budget_usd=$5.00 stops it.
#   Set max_hops in the spec for a provable bound.
from langgraph.graph import END, START, StateGraph
from langgraph.checkpoint.memory import MemorySaver

from breakerbox import guard


def agent(state):  # model: openai/gpt-4o · max_tokens=1024 · sub_budget=unset
    # TODO: call your model here and update state
    return state


def loop(state):  # router: keep_going
    # TODO: (optional) prep state before routing
    return state


def loop_route(state):
    # TODO: return one of: again, done
    return "again"


builder = StateGraph(dict)
builder.add_node("agent", agent)
builder.add_node("loop", loop)
builder.add_edge(START, "agent")
builder.add_edge("agent", "loop")
builder.add_conditional_edges("loop", loop_route, {"again": "agent", "done": END})

app = guard(
    builder.compile(checkpointer=MemorySaver()),
    budget_usd=5.0,
    on_trip="pause",
)

if __name__ == "__main__":
    print(app.invoke({}))
