# Generated by Breakerbox Builder. Edit the node bodies marked TODO.
from langgraph.graph import END, START, StateGraph
from langgraph.checkpoint.memory import MemorySaver

from breakerbox import guard


def planner(state):  # model: openai/gpt-4o · max_tokens=512 · sub_budget=unset
    resp = call_model(state["messages"])

    state["messages"].append(resp)
    return state


def fetch(state):  # tool: web_search · side_effecting=False
    state["docs"] = web_search(state["query"])
    return state


def summarize(state):  # model: anthropic/claude-sonnet-4-6 · max_tokens=default · sub_budget=unset
    # TODO: call your model here and update state
    return state


builder = StateGraph(dict)
builder.add_node("planner", planner)
builder.add_node("fetch", fetch)
builder.add_node("summarize", summarize)
builder.add_edge(START, "planner")
builder.add_edge("planner", "fetch")
builder.add_edge("fetch", "summarize")
builder.add_edge("summarize", END)

app = guard(
    builder.compile(checkpointer=MemorySaver()),
    budget_usd=3.0,
    on_trip="kill",
)

if __name__ == "__main__":
    print(app.invoke({}))
